# Generated by Django 3.1.5 on 2021-01-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_text',
        ),
    ]
